"""empty message

Revision ID: f1a4e95b78e0
Revises: 
Create Date: 2020-07-01 17:39:10.112548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a4e95b78e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('coordenadas', sa.String(length=50), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('birthdate', sa.String(length=15), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gruposangre', sa.String(length=15), nullable=True),
    sa.Column('alergia', sa.String(length=100), nullable=True),
    sa.Column('enfermedadbase', sa.String(length=100), nullable=True),
    sa.Column('contactouno', sa.String(length=20), nullable=True),
    sa.Column('contactodos', sa.String(length=20), nullable=True),
    sa.Column('telcontuno', sa.String(length=20), nullable=True),
    sa.Column('telcontdos', sa.String(length=20), nullable=True),
    sa.Column('clinica', sa.String(length=100), nullable=True),
    sa.Column('medicamentos', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numpago', sa.String(length=100), nullable=True),
    sa.Column('asistencia', sa.Boolean(), nullable=True),
    sa.Column('fechacompra', sa.String(length=10), nullable=True),
    sa.Column('fechapago', sa.String(length=10), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('emergencia')
    op.drop_table('user')
    op.drop_table('roles')
    # ### end Alembic commands ###
